### PR TITLE
Update EntsoeAPI.cs

### PR DESCRIPTION
**Pull request by simonepittis**
We need to update this too
https://transparency.entsoe.eu/content/static_content/Static%20content/web%20api/Guide.html#_load_domain

:-)

### CODE REVIEW

**Comment by simonepittis** [comment]
I added too the NO-0 and deleted the NO-5

**Comment by simonepittis** [comment]
mmmm but NO-5 it's Bergen...

**Comment by simonepittis** [comment]
Ok Find it
BZN|NO5 = 10Y1001A1001A48H

**Comment by simonepittis** [comment]
https://web-api.tp.entsoe.eu/api?documentType=A44&in_Domain=10Y1001A1001A48H&out_Domain=10Y1001A1001A48H&periodStart=202303220000&periodEnd=202303230000&securityToken=5cd1c4f6-2172-4453-a8bb-c9467fa0fabc

**Comment by gmeks** [comment]
My current setup with local gitea server, that syncs to github is apprently not a good optimal, You changes are in code but your commit history might not show :(

**Pull request merged**
